"""Add therapist and model changes

Revision ID: 872d8eecbb10
Revises: 
Create Date: 2025-09-15 19:25:45.256634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '872d8eecbb10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_messages_flow'), table_name='chat_messages')
    op.drop_column('chat_messages', 'conversation_flow')
    op.drop_column('chat_messages', 'response_quality_score')
    op.drop_index(op.f('idx_sessions_summary'), table_name='chat_sessions', postgresql_where='(conversation_summary IS NOT NULL)')
    op.drop_column('chat_sessions', 'context_metadata')
    op.add_column('community_posts', sa.Column('community_id', sa.UUID(), nullable=True))
    op.add_column('community_posts', sa.Column('toxicity_score', sa.Float(), nullable=True))
    op.add_column('community_posts', sa.Column('harmful_categories', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_community_posts_community_id'), 'community_posts', ['community_id'], unique=False)
    op.create_foreign_key(None, 'community_posts', 'communities', ['community_id'], ['id'], ondelete='CASCADE')
    op.add_column('crisis_alerts', sa.Column('assigned_therapist_id', sa.UUID(), nullable=True))
    op.create_index('idx_crisis_assigned_therapist', 'crisis_alerts', ['assigned_therapist_id'], unique=False)
    op.create_index(op.f('ix_crisis_alerts_assigned_therapist_id'), 'crisis_alerts', ['assigned_therapist_id'], unique=False)
    op.add_column('therapists', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_therapists_phone_number'), 'therapists', ['phone_number'], unique=True)
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'phone_number')
    op.drop_index(op.f('ix_therapists_phone_number'), table_name='therapists')
    op.drop_column('therapists', 'phone_number')
    op.drop_index(op.f('ix_crisis_alerts_assigned_therapist_id'), table_name='crisis_alerts')
    op.drop_index('idx_crisis_assigned_therapist', table_name='crisis_alerts')
    op.drop_column('crisis_alerts', 'assigned_therapist_id')
    op.drop_constraint(None, 'community_posts', type_='foreignkey')
    op.drop_index(op.f('ix_community_posts_community_id'), table_name='community_posts')
    op.drop_column('community_posts', 'harmful_categories')
    op.drop_column('community_posts', 'toxicity_score')
    op.drop_column('community_posts', 'community_id')
    op.add_column('chat_sessions', sa.Column('context_metadata', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_sessions_summary'), 'chat_sessions', ['user_id', 'last_message_at'], unique=False, postgresql_where='(conversation_summary IS NOT NULL)')
    op.add_column('chat_messages', sa.Column('response_quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('conversation_flow', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_messages_flow'), 'chat_messages', ['session_id', 'conversation_flow', 'created_at'], unique=False)
    # ### end Alembic commands ###
